//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pre_examen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPollo
    {
        public int IDtipo { get; set; }
        public string TipoDePollo { get; set; }
        public int IDcategoria { get; set; }
    }
}
